// prompt.js — builds the system prompt exactly per spec section 5.
// Loaded as a classic script by content.js (no ES modules, to keep injection simple).

const COH_TYPO_TIERS = {
  low: { count: 2, label: "Low" },
  medium: { count: 4, label: "Medium" },
  high: { count: 7, label: "High" }
};

function coh_buildPrompt({ text, tone, typoTier, lowercase, additionalInstructions }) {
  const typo = COH_TYPO_TIERS[typoTier] || COH_TYPO_TIERS.medium;
  const highExtra =
    typoTier === "high"
      ? `\n- one doubled or dropped letter in a longer word, allowed`
      : "";

  const step6 = additionalInstructions
    ? `\nSTEP 6 — ADDITIONAL USER INSTRUCTIONS\nApply these on top of everything above, without breaking the rules already given: "${additionalInstructions.replace(/"/g, '\\"')}"\n`
    : "";

  return `You are rewriting a cold email/DM so it reads like it was typed quickly by a real person, not generated by AI. Follow these steps in order.

INPUT TEXT:
"""
${text}
"""

STEP 1 — REWRITE FOR TONE
Rewrite the wording to match this tone: ${tone}  // "professional" or "conversational"
Do this unconditionally — rewrite regardless of what tone the input is already in. Keep the same meaning, same ask, same length (do not pad or shorten significantly).

STEP 2 — REMOVE AI TELLS (always apply, regardless of tone)
- Remove all em dashes and hyphens used as sentence connectors (" - ", " — "). Replace with a comma, period, or split into two short sentences.
- Remove all emojis.
- Do not use any of these words/phrases: [hope this finds you well, delve, furthermore, leverage, seamless, robust, unlock, game-changer, in today's fast-paced world, I wanted to reach out, circle back, touch base]
- Avoid three-part parallel lists ("fast, reliable, and scalable"). Break the rhythm — vary sentence length, some short and blunt, some longer.
- Reduce semicolons and non-essential commas. Real fast-typed messages under-punctuate, not over-punctuate.

STEP 3 — LOWERCASE MODE: ${lowercase ? "true" : "false"}
If true: rewrite the entire message in lowercase, including no longer capitalizing the first letter of each sentence. Exceptions stay capitalized: proper nouns, the word "I", and acronyms.
If false: skip this step entirely — normal sentence-initial capitalization stays untouched.

STEP 4 — TYPOS
Apply exactly ${typo.count} typos total, no more, no fewer, using ONLY these categories:
- common misspellings of everyday words
- dropped apostrophes in contractions
- swapped homophones (their/there/they're, your/you're)
- occasional missing comma before "and"/"but"${highExtra}

Never place a typo in:
- proper nouns, company names, or the recipient's name
- numbers, dates, prices, URLs, or email addresses
- the first line (greeting) or the last line (sign-off/CTA)

STEP 5 — FORMAT PRESERVATION
Keep the same number of paragraphs and line breaks as the input. Keep the greeting and sign-off lines in their original position.
${step6}
OUTPUT DIRECTION:
Provide ONLY the final rewritten text. Do not include any JSON wrapping, markdown formatting codes, or introductory sentences. Start directly with the rewritten text.`;
}